### ISSUE TITLE
getAudio() only is getting 76800 bytes in the first loop

### ISSUE THREAD

**Issue by ghost** [ShuaiShao93/Audio-Capture-Transmission-Player#2]
Hi again,

I'm opening a new issue because I found out in **AudioHook2** project the core of problem of why **getAudio()** is getting **76800** bytes only in the first loop. 

So, let's get started:

1 - Calling **getAudio()**, in **Sender.pp** on  **AudioHook2** project, the **getDataSize()** function returns:
**76800==MAXLENGTH**
Because **isEmpty** is **0**
https://github.com/ShuaiShao93/Audio-Capture-Transmission-Player/blob/32235fe54af4f8437081b3e01c98a00c6a1279da/AudioHook/Sender.cpp#L166

2 - Then in the while loop in **getAll()** function in **getAudio.cpp** numBytes accumulates until it achieves **76800**.
https://github.com/ShuaiShao93/Audio-Capture-Transmission-Player/blob/32235fe54af4f8437081b3e01c98a00c6a1279da/AudioHook/getAudio.cpp#L80

3 - Next, it enters in **if** bellow and **pOldest** receives numBytes= **76800**.
https://github.com/ShuaiShao93/Audio-Capture-Transmission-Player/blob/32235fe54af4f8437081b3e01c98a00c6a1279da/AudioHook/getAudio.cpp#L93

4 - It finishes the **getAudio()** call returning numBytes= **76800** and with:
 pLastest= **0**
pOldest= **76800**
isEmpty= **0**

5 - Next, calling the **getAudio()** again, in the **sender.cpp** the **getDataSize()** returns **0**, because the **if** bellow:
https://github.com/ShuaiShao93/Audio-Capture-Transmission-Player/blob/32235fe54af4f8437081b3e01c98a00c6a1279da/AudioHook/Sender.cpp#L163

6 - So, numBytes not accumulate in the while loop and it keeps the **0** value.
https://github.com/ShuaiShao93/Audio-Capture-Transmission-Player/blob/32235fe54af4f8437081b3e01c98a00c6a1279da/AudioHook/getAudio.cpp#L80

7 - So, it enters in the **if** bellow again the **pOldest** receives numBytes = **0**.
https://github.com/ShuaiShao93/Audio-Capture-Transmission-Player/blob/32235fe54af4f8437081b3e01c98a00c6a1279da/AudioHook/getAudio.cpp#L93

8 - So, it enters in **if** bellow and isEmpty receive **1**.
https://github.com/ShuaiShao93/Audio-Capture-Transmission-Player/blob/32235fe54af4f8437081b3e01c98a00c6a1279da/AudioHook/getAudio.cpp#L104

9 - It finishes the **getAudio()** call returning numBytes= **0** and with:
 pLastest= **0**
pOldest= **0**
isEmpty= **1**

10 - Calling **getAudio()** again, in **sender.cpp** the **getDataSize()** returns **0**:
https://github.com/ShuaiShao93/Audio-Capture-Transmission-Player/blob/32235fe54af4f8437081b3e01c98a00c6a1279da/AudioHook/Sender.cpp#L166
Because isEmpty is **1** and 

11- In the while loop numBytes not accumulate and then it keeps the **0** value:
 https://github.com/ShuaiShao93/Audio-Capture-Transmission-Player/blob/32235fe54af4f8437081b3e01c98a00c6a1279da/AudioHook/getAudio.cpp#L80

12- Next, it enters in **if** bellow:
https://github.com/ShuaiShao93/Audio-Capture-Transmission-Player/blob/32235fe54af4f8437081b3e01c98a00c6a1279da/AudioHook/getAudio.cpp#L83
and pOldest receive numBytes= **0**.

13 - Next, it enters in **if** bellow too:
https://github.com/ShuaiShao93/Audio-Capture-Transmission-Player/blob/32235fe54af4f8437081b3e01c98a00c6a1279da/AudioHook/getAudio.cpp#L104
and the isEmpty receive **1** again.

14 - It finishes **getAudio()** returning numBytes **0** and with:
 pLastest= **0**
pOldest= **0**
isEmpty= **1**

So, we have a infinite loop with numBytes returning **0**.

**Comment by ShuaiShao93** [comment]
Hi, did you see my comment in the last issue? You need to make it sleep for some time to wait for some audio accumulating in the buffer, so that the numBytes returned by getAudio() won't be 0.

**Comment by ShuaiShao93** [comment]
In the 5th step, getDataSize() shouldn't return 0 because the DLL keeps filling the buffer by calling FillSenderBuffer(). https://github.com/ShuaiShao93/Audio-Capture-Transmission-Player/blob/32235fe54af4f8437081b3e01c98a00c6a1279da/AudioHook/Sender.cpp#L105

I found another potential problem. Did you see AudioHook2.lib file under /TestCaptureAudio? I think you need to build your own AudioHook2.lib, which is generated together with AudioHook2.dll, and replace the previous AudioHook2.lib under /TestCaptureAudio with new one. It will be used to build TestCaptureAudio. Because I'm not sure if lib file is still same under different compiling environment, otherwise the getAudio() interface may be broken.

btw, all projects should be consistent on debug/release build.

**Comment by ghost** [comment]
Oh my gosh..
Sorry by didn't tell you since the beginning. I built all the projects and I replaced the path
https://github.com/ShuaiShao93/Audio-Capture-Transmission-Player/blob/0f5ccaa028c3bf2d3d6a0f19030de8d4ddda5536/InjectDLL/InjectDLL.cpp#L25
by the right path which **AudioHook** built **AudioHook2.dll** and all the **dependencies**. 
And when I ran **TestCaptureAudio.exe** by the first time it complainted **"the AudioHook2.dll was not found in your system [...]"**. So I worked this issue around copying only **AudioHook2.dll** into the **"\TestCaptureAudio\Release"** folder and I went on coding and getting all this issues until now.

So, answer your question, until now I didn't replace **AudioHook2.lib** in  /TestCaptureAudio. I will try that.

Meanwhile If you could build the project in your computer, please let me know about.

**Comment by ghost** [comment]
Did you read the last issue where I said that **TestCaptureAudio** after the build failed to find out AudioHook2.dll (even after I have rebuild AudioHook and copy/paste AudioHook2.lib to the TestCaptureAudio folder )?
  
Update: I did that after undo all the projects to original settings. 

Update 2: do you have skype, hangout ou Facebook messenger to talk? You can send in private to my GitHub user.

**Comment by ShuaiShao93** [comment]
Hi, sorry for the late reply. I just managed to run it on my computer. And I updated a clearer version for the whole project, including README file. I think your issue might be caused by DLL file. Could you read the 4th and 5th step in README.md, move dll to TestCaptureAudio\Release, and point the path in InjectDLL to it? Note that dll must be put in the same folder with TestCaptureAudio.exe, and InjectDLL must inject the same dll into process.

If that still doesn't work, maybe you could try pulling the new version and following the steps in README.md.

**Comment by ghost** [comment]
Thanks. It finally worked. 


Update: If you want to close the issue. It's ok.
